export type EconomicsTermCategory =
  | "core"
  | "consumer"
  | "demand"
  | "production"
  | "cost"
  | "market"
  | "welfare";

export type EconomicsTerm = {
  id: string;
  english: string;
  chinese: string;
  aliases: string[];
  category: EconomicsTermCategory;
  chapter: string;
  plainMeaning: string;
  translationNote: string;
  examHint: string;
  related: string[];
};

export const economicsCategoryLabels: Record<EconomicsTermCategory, string> = {
  core: "基础概念",
  consumer: "消费者理论",
  demand: "需求与弹性",
  production: "生产理论",
  cost: "成本理论",
  market: "市场结构",
  welfare: "福利分析",
};

export const economicsTerms: EconomicsTerm[] = [
  {
    id: "marginal",
    english: "marginal",
    chinese: "边际",
    aliases: ["边际", "marginal"],
    category: "core",
    chapter: "导论 / 消费者与生产者决策",
    plainMeaning: "多增加一单位时，总量发生的额外变化。",
    translationNote: "它不是中文直觉里的“边缘”，核心是“再多一点会怎样”。",
    examHint: "看到边际，优先想增量、斜率、一阶条件，而不是平均值。",
    related: ["marginal-utility", "marginal-cost", "marginal-product"],
  },
  {
    id: "utility",
    english: "utility",
    chinese: "效用",
    aliases: ["效用", "utility"],
    category: "consumer",
    chapter: "消费者行为",
    plainMeaning: "消费者从商品组合中获得的满足程度或偏好排序。",
    translationNote: "utility 不一定是可精确测量的快乐，更常用于表示偏好顺序。",
    examHint: "考题里通常不需要解释心理感受，重点是偏好、无差异曲线和最优选择。",
    related: ["preference", "marginal-utility", "indifference-curve"],
  },
  {
    id: "marginal-utility",
    english: "marginal utility",
    chinese: "边际效用",
    aliases: ["边际效用", "marginal utility", "MU"],
    category: "consumer",
    chapter: "消费者行为",
    plainMeaning: "多消费一单位某商品带来的额外效用。",
    translationNote: "关键不是“效用有多大”，而是“多一单位增加了多少”。",
    examHint: "和价格结合时常出现等边际原则：每一元钱带来的边际效用相等。",
    related: ["utility", "marginal", "marginal-rate-of-substitution"],
  },
  {
    id: "preference",
    english: "preference",
    chinese: "偏好",
    aliases: ["偏好", "preference", "preferences"],
    category: "consumer",
    chapter: "消费者行为",
    plainMeaning: "消费者对不同商品组合的排序关系。",
    translationNote: "preference 是“更喜欢哪一个”的排序，不等于实际买了什么。",
    examHint: "区分 preference 和 choice：前者是排序，后者是预算约束下的实际选择。",
    related: ["choice", "utility", "indifference-curve"],
  },
  {
    id: "choice",
    english: "choice",
    chinese: "选择",
    aliases: ["选择", "choice"],
    category: "consumer",
    chapter: "消费者行为",
    plainMeaning: "在约束条件下实际选出的商品组合。",
    translationNote: "choice 受预算约束影响，所以不一定等于最想要的组合。",
    examHint: "写消费者最优时，要同时写偏好目标和预算约束。",
    related: ["preference", "budget-constraint", "utility"],
  },
  {
    id: "indifference-curve",
    english: "indifference curve",
    chinese: "无差异曲线",
    aliases: ["无差异曲线", "indifference curve", "indifference curves"],
    category: "consumer",
    chapter: "消费者行为",
    plainMeaning: "让消费者感到同样满意的一组商品组合。",
    translationNote: "“无差异”不是没有区别，而是消费者评价上同等满意。",
    examHint: "斜率的绝对值通常对应边际替代率。",
    related: ["marginal-rate-of-substitution", "utility", "preference"],
  },
  {
    id: "marginal-rate-of-substitution",
    english: "marginal rate of substitution",
    chinese: "边际替代率",
    aliases: ["边际替代率", "marginal rate of substitution", "MRS"],
    category: "consumer",
    chapter: "消费者行为",
    plainMeaning: "为多得到一单位某商品，消费者愿意放弃另一商品的数量。",
    translationNote: "它表达的是主观愿意交换的比例，不是市场价格比例。",
    examHint: "消费者最优常写成 MRS 等于价格比。",
    related: ["indifference-curve", "budget-constraint", "marginal-utility"],
  },
  {
    id: "budget-constraint",
    english: "budget constraint",
    chinese: "预算约束",
    aliases: ["预算约束", "预算线", "budget constraint", "budget line"],
    category: "consumer",
    chapter: "消费者行为",
    plainMeaning: "收入和价格限制了消费者买得起的商品组合。",
    translationNote: "constraint 更接近“限制条件”，不是简单的一条线。",
    examHint: "价格变化会旋转预算线，收入变化会平移预算线。",
    related: ["choice", "income-effect", "substitution-effect"],
  },
  {
    id: "income-effect",
    english: "income effect",
    chinese: "收入效应",
    aliases: ["收入效应", "income effect"],
    category: "demand",
    chapter: "需求分析",
    plainMeaning: "价格变化改变实际购买力后，引起的消费量变化。",
    translationNote: "这里的 income 不一定是名义收入变了，而是实际购买力变了。",
    examHint: "和替代效应一起拆解价格变化对需求量的影响。",
    related: ["substitution-effect", "budget-constraint", "normal-good"],
  },
  {
    id: "substitution-effect",
    english: "substitution effect",
    chinese: "替代效应",
    aliases: ["替代效应", "substitution effect"],
    category: "demand",
    chapter: "需求分析",
    plainMeaning: "相对价格变化后，消费者用相对便宜的商品替代相对昂贵的商品。",
    translationNote: "核心是相对价格变化，不是收入购买力变化。",
    examHint: "正常品、劣等品、吉芬商品的判断常依赖这两个效应方向。",
    related: ["income-effect", "budget-constraint", "demand"],
  },
  {
    id: "demand",
    english: "demand",
    chinese: "需求",
    aliases: ["需求", "需求曲线", "demand", "demand curve"],
    category: "demand",
    chapter: "供给与需求",
    plainMeaning: "在各种价格下消费者愿意且能够购买的数量关系。",
    translationNote: "demand 是一整条关系，不是某一个价格下的购买量。",
    examHint: "区分需求变动和需求量变动：前者整条曲线移动，后者沿曲线移动。",
    related: ["quantity-demanded", "elasticity", "substitution-effect"],
  },
  {
    id: "quantity-demanded",
    english: "quantity demanded",
    chinese: "需求量",
    aliases: ["需求量", "quantity demanded"],
    category: "demand",
    chapter: "供给与需求",
    plainMeaning: "在某一个价格水平下消费者愿意且能够购买的具体数量。",
    translationNote: "quantity demanded 是点，demand 是价格和数量的关系。",
    examHint: "价格自身变化通常说需求量变动，不说需求变动。",
    related: ["demand", "elasticity"],
  },
  {
    id: "elasticity",
    english: "elasticity",
    chinese: "弹性",
    aliases: ["弹性", "elasticity"],
    category: "demand",
    chapter: "需求与弹性",
    plainMeaning: "一个变量变化百分之一时，另一个变量变化多少百分比。",
    translationNote: "elasticity 是敏感程度，不是物理意义的弹力。",
    examHint: "弹性通常用百分比变化比，避免单位影响。",
    related: ["price-elasticity-of-demand", "income-elasticity"],
  },
  {
    id: "price-elasticity-of-demand",
    english: "price elasticity of demand",
    chinese: "需求价格弹性",
    aliases: ["需求价格弹性", "价格弹性", "price elasticity of demand", "PED"],
    category: "demand",
    chapter: "需求与弹性",
    plainMeaning: "商品价格变化百分之一时，需求量变化多少百分比。",
    translationNote: "它衡量需求量对价格的敏感度，不是需求曲线斜率本身。",
    examHint: "总收益与价格同向还是反向变化，常由需求价格弹性判断。",
    related: ["elasticity", "quantity-demanded", "demand"],
  },
  {
    id: "income-elasticity",
    english: "income elasticity of demand",
    chinese: "需求收入弹性",
    aliases: ["需求收入弹性", "income elasticity", "income elasticity of demand"],
    category: "demand",
    chapter: "需求与弹性",
    plainMeaning: "收入变化百分之一时，需求量变化多少百分比。",
    translationNote: "用来区分正常品、劣等品和奢侈品等需求特征。",
    examHint: "符号和大小都重要：小于零通常对应劣等品。",
    related: ["elasticity", "normal-good", "inferior-good"],
  },
  {
    id: "normal-good",
    english: "normal good",
    chinese: "正常品",
    aliases: ["正常品", "normal good", "normal goods"],
    category: "demand",
    chapter: "需求分析",
    plainMeaning: "收入上升时需求量增加的商品。",
    translationNote: "normal 不是质量正常，而是需求随收入同向变化。",
    examHint: "正常品的收入效应与价格变动方向通常相反。",
    related: ["income-elasticity", "inferior-good", "income-effect"],
  },
  {
    id: "inferior-good",
    english: "inferior good",
    chinese: "劣等品",
    aliases: ["劣等品", "低档品", "inferior good", "inferior goods"],
    category: "demand",
    chapter: "需求分析",
    plainMeaning: "收入上升时需求量反而下降的商品。",
    translationNote: "inferior 不是道德或质量评价，而是收入需求关系的分类。",
    examHint: "劣等品不必然是吉芬商品，吉芬商品需要收入效应压过替代效应。",
    related: ["normal-good", "income-effect", "giffen-good"],
  },
  {
    id: "giffen-good",
    english: "Giffen good",
    chinese: "吉芬商品",
    aliases: ["吉芬商品", "Giffen good", "Giffen goods"],
    category: "demand",
    chapter: "需求分析",
    plainMeaning: "价格上升时需求量反而上升的特殊劣等品。",
    translationNote: "它不是炫耀性消费，重点是强烈收入效应压过替代效应。",
    examHint: "判断时写清楚：劣等品 + 收入效应足够强。",
    related: ["inferior-good", "income-effect", "substitution-effect"],
  },
  {
    id: "marginal-product",
    english: "marginal product",
    chinese: "边际产量",
    aliases: ["边际产量", "边际产品", "marginal product", "MP"],
    category: "production",
    chapter: "生产理论",
    plainMeaning: "多投入一单位某生产要素带来的额外产出。",
    translationNote: "product 在这里是产出结果，不是商品本身。",
    examHint: "短期生产函数里常和边际报酬递减一起出现。",
    related: ["diminishing-marginal-returns", "marginal", "production-function"],
  },
  {
    id: "diminishing-marginal-returns",
    english: "diminishing marginal returns",
    chinese: "边际报酬递减",
    aliases: ["边际报酬递减", "边际收益递减", "diminishing marginal returns"],
    category: "production",
    chapter: "生产理论",
    plainMeaning: "其他投入固定时，继续增加一种投入，其新增产出最终会下降。",
    translationNote: "returns 这里是投入带来的产出回报，不是利润收益。",
    examHint: "限定条件是至少有一种要素固定，常见于短期生产。",
    related: ["marginal-product", "production-function", "returns-to-scale"],
  },
  {
    id: "returns-to-scale",
    english: "returns to scale",
    chinese: "规模报酬",
    aliases: ["规模报酬", "returns to scale"],
    category: "production",
    chapter: "生产理论",
    plainMeaning: "所有投入同比例变化时，产出如何变化。",
    translationNote: "scale 指整体生产规模，不是单个要素投入。",
    examHint: "和边际报酬递减区分：规模报酬讨论所有投入同时变动。",
    related: ["economies-of-scale", "diminishing-marginal-returns", "production-function"],
  },
  {
    id: "isoquant",
    english: "isoquant",
    chinese: "等产量线",
    aliases: ["等产量线", "isoquant", "isoquants"],
    category: "production",
    chapter: "生产理论",
    plainMeaning: "能够生产同一产量的不同投入组合。",
    translationNote: "iso 表示相同，quant 对应数量或产量。",
    examHint: "可和消费者理论里的无差异曲线类比，但含义是产量而不是效用。",
    related: ["isocost", "marginal-product", "production-function"],
  },
  {
    id: "isocost",
    english: "isocost line",
    chinese: "等成本线",
    aliases: ["等成本线", "isocost", "isocost line"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "在同一成本支出下可以购买的不同投入组合。",
    translationNote: "它是生产者问题中的约束线，类似消费者预算线。",
    examHint: "成本最小化常写成等产量线与等成本线相切。",
    related: ["isoquant", "marginal-cost", "economies-of-scale"],
  },
  {
    id: "opportunity-cost",
    english: "opportunity cost",
    chinese: "机会成本",
    aliases: ["机会成本", "opportunity cost"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "做出一个选择时放弃的最有价值替代方案。",
    translationNote: "cost 不只包括会计账面支出，也包括被放弃的机会。",
    examHint: "经济成本通常包含显性成本和隐性成本。",
    related: ["explicit-cost", "implicit-cost", "economic-profit"],
  },
  {
    id: "explicit-cost",
    english: "explicit cost",
    chinese: "显性成本",
    aliases: ["显性成本", "explicit cost", "explicit costs"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "企业实际支付出去、账面上可见的成本。",
    translationNote: "explicit 是明示的、外显的，不需要推算。",
    examHint: "会计利润一般只扣除显性成本。",
    related: ["implicit-cost", "opportunity-cost", "economic-profit"],
  },
  {
    id: "implicit-cost",
    english: "implicit cost",
    chinese: "隐性成本",
    aliases: ["隐性成本", "implicit cost", "implicit costs"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "没有直接支付但代表被放弃机会的成本。",
    translationNote: "implicit 是隐含的，通常要通过机会成本理解。",
    examHint: "经济利润要扣除显性成本和隐性成本。",
    related: ["explicit-cost", "opportunity-cost", "economic-profit"],
  },
  {
    id: "marginal-cost",
    english: "marginal cost",
    chinese: "边际成本",
    aliases: ["边际成本", "marginal cost", "MC"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "多生产一单位产量带来的额外总成本。",
    translationNote: "它看的是新增一单位的成本，不是平均每单位成本。",
    examHint: "利润最大化与市场供给分析里经常用 MC。",
    related: ["average-cost", "marginal", "producer-surplus"],
  },
  {
    id: "average-cost",
    english: "average cost",
    chinese: "平均成本",
    aliases: ["平均成本", "average cost", "AC", "ATC", "average total cost"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "总成本除以产量得到的每单位平均成本。",
    translationNote: "average 是摊到每单位的水平，和 marginal 的增量视角不同。",
    examHint: "MC 小于 AC 时 AC 下降，MC 大于 AC 时 AC 上升。",
    related: ["marginal-cost", "fixed-cost", "variable-cost"],
  },
  {
    id: "fixed-cost",
    english: "fixed cost",
    chinese: "固定成本",
    aliases: ["固定成本", "fixed cost", "fixed costs", "FC"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "短期内不随产量变化而变化的成本。",
    translationNote: "fixed 是相对于当前决策期固定，不代表永远不变。",
    examHint: "停产决策里常看价格能否覆盖平均可变成本，而不是固定成本。",
    related: ["variable-cost", "average-cost", "sunk-cost"],
  },
  {
    id: "variable-cost",
    english: "variable cost",
    chinese: "可变成本",
    aliases: ["可变成本", "variable cost", "variable costs", "VC"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "随产量变化而变化的成本。",
    translationNote: "variable 强调会随产量调整，不是说数值随机波动。",
    examHint: "短期停产点通常与平均可变成本有关。",
    related: ["fixed-cost", "average-cost", "marginal-cost"],
  },
  {
    id: "sunk-cost",
    english: "sunk cost",
    chinese: "沉没成本",
    aliases: ["沉没成本", "sunk cost", "sunk costs"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "已经发生且无法收回的成本。",
    translationNote: "sunk 是已经沉下去，当前决策不应再被它左右。",
    examHint: "理性决策通常忽略沉没成本，关注未来边际收益和边际成本。",
    related: ["fixed-cost", "opportunity-cost", "marginal-cost"],
  },
  {
    id: "economies-of-scale",
    english: "economies of scale",
    chinese: "规模经济",
    aliases: ["规模经济", "economies of scale"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "产量扩大时，长期平均成本下降。",
    translationNote: "economies 这里不是经济学整体，而是节约或成本优势。",
    examHint: "和规模报酬区分：规模经济看成本，规模报酬看投入产出关系。",
    related: ["returns-to-scale", "average-cost", "isocost"],
  },
  {
    id: "producer-surplus",
    english: "producer surplus",
    chinese: "生产者剩余",
    aliases: ["生产者剩余", "producer surplus"],
    category: "welfare",
    chapter: "福利分析",
    plainMeaning: "生产者实际收到的价格超过其愿意接受最低价格的部分。",
    translationNote: "surplus 是超出保留价格的剩余收益，不等同于会计利润。",
    examHint: "供给曲线以上、市场价格以下的区域常表示生产者剩余。",
    related: ["consumer-surplus", "marginal-cost", "deadweight-loss"],
  },
  {
    id: "consumer-surplus",
    english: "consumer surplus",
    chinese: "消费者剩余",
    aliases: ["消费者剩余", "consumer surplus"],
    category: "welfare",
    chapter: "福利分析",
    plainMeaning: "消费者愿意支付的最高价格超过实际支付价格的部分。",
    translationNote: "surplus 是交易带来的净好处，不是消费者手里剩下的钱。",
    examHint: "需求曲线以下、市场价格以上的区域常表示消费者剩余。",
    related: ["producer-surplus", "welfare", "deadweight-loss"],
  },
  {
    id: "deadweight-loss",
    english: "deadweight loss",
    chinese: "无谓损失",
    aliases: ["无谓损失", "净损失", "deadweight loss", "DWL"],
    category: "welfare",
    chapter: "福利分析",
    plainMeaning: "市场扭曲导致本可实现但没有实现的总剩余损失。",
    translationNote: "deadweight 指无法转移给任何一方的效率损失。",
    examHint: "税收、价格管制、垄断等都可能产生无谓损失。",
    related: ["consumer-surplus", "producer-surplus", "market-equilibrium"],
  },
  {
    id: "market-equilibrium",
    english: "market equilibrium",
    chinese: "市场均衡",
    aliases: ["市场均衡", "均衡价格", "均衡数量", "market equilibrium", "equilibrium price"],
    category: "market",
    chapter: "供给与需求",
    plainMeaning: "供给量与需求量相等时形成的价格和数量。",
    translationNote: "equilibrium 是力量相互抵消后的状态，不是永远不变。",
    examHint: "比较静态题通常问冲击后均衡价格和数量如何变动。",
    related: ["demand", "quantity-demanded", "deadweight-loss"],
  },
  {
    id: "economic-profit",
    english: "economic profit",
    chinese: "经济利润",
    aliases: ["经济利润", "economic profit"],
    category: "cost",
    chapter: "成本理论",
    plainMeaning: "总收益扣除显性成本和隐性成本后的利润。",
    translationNote: "经济利润比会计利润更严格，因为它扣除了机会成本。",
    examHint: "长期竞争均衡中经济利润为零，并不等于会计利润为零。",
    related: ["explicit-cost", "implicit-cost", "opportunity-cost"],
  },
  {
    id: "production-function",
    english: "production function",
    chinese: "生产函数",
    aliases: ["生产函数", "production function"],
    category: "production",
    chapter: "生产理论",
    plainMeaning: "投入组合与最大可实现产出之间的技术关系。",
    translationNote: "function 强调技术约束下的映射关系，不是企业主观目标。",
    examHint: "常用来分析边际产量、规模报酬和成本最小化。",
    related: ["marginal-product", "returns-to-scale", "isoquant"],
  },
  {
    id: "welfare",
    english: "welfare",
    chinese: "福利",
    aliases: ["福利", "welfare", "social welfare"],
    category: "welfare",
    chapter: "福利分析",
    plainMeaning: "经济学中衡量各方收益或总剩余的概念。",
    translationNote: "welfare 在微观里常指福利水平或社会总剩余，不只是社会救济。",
    examHint: "福利分析一般围绕消费者剩余、生产者剩余和无谓损失展开。",
    related: ["consumer-surplus", "producer-surplus", "deadweight-loss"],
  },
];

export function getEconomicsTermSearchText(term: EconomicsTerm): string {
  return [
    term.english,
    term.chinese,
    ...term.aliases,
    economicsCategoryLabels[term.category],
    term.chapter,
    term.plainMeaning,
    term.translationNote,
    term.examHint,
  ].join(" ");
}

export function getEconomicsTermById(id: string): EconomicsTerm | undefined {
  return economicsTerms.find((term) => term.id === id);
}

export function getEconomicsTermAliases(term: EconomicsTerm): string[] {
  return Array.from(new Set([term.english, term.chinese, ...term.aliases]))
    .map((alias) => alias.trim())
    .filter(Boolean);
}
