import { Note } from './types';

// 演示文章 1: 笔记类型 - 展示目录、视频、AI助手、标签编辑、封面等功能
const noteContent1 = [
  '# 微积分基础',
  '',
  '## 函数与极限',
  '',
  '### 函数的基本概念',
  '函数是描述变量之间依赖关系的数学工具。设 $D$ 是一个非空实数集合，如果按照某种对应法则 $f$，对于 $D$ 中的每一个实数 $x$，都有唯一确定的实数 $y$ 与之对应，则称 $f$ 是定义在 $D$ 上的函数。',
  '',
  '### 极限的定义',
  '数列极限：对于数列 {a_n}，如果存在常数 $a$，使得对于任意给定的正数 $\\varepsilon$，总存在正整数 $N$，当 $n > N$ 时，恒有 $|a_n - a| < \\varepsilon$，则称数列 {a_n} 收敛于 $a$。',
  '',
  '函数极限：$\lim_{x \\to x_0} f(x) = A$ 的 $\\varepsilon-\\delta$ 定义。',
  '',
  '## 导数与微分',
  '',
  '### 导数的概念',
  '导数是函数在某一点处的变化率，几何意义是曲线在该点处切线的斜率。',
  '',
  '定义：$f\'(x_0) = \\lim_{\\Delta x \\to 0} \\frac{f(x_0 + \\Delta x) - f(x_0)}{\\Delta x}$',
  '',
  '### 基本求导公式',
  '- $(x^n)\' = nx^{n-1}$',
  '- $(\\sin x)\' = \\cos x$',
  '- $(\\cos x)\' = -\\sin x$',
  '- $(e^x)\' = e^x$',
  '- $(\\ln x)\' = \\frac{1}{x}$',
  '',
  '## 积分学',
  '',
  '### 不定积分',
  '不定积分是求导的逆运算。若 $F\'(x) = f(x)$，则 $F(x) + C$ 称为 $f(x)$ 的不定积分，记作：',
  '',
  '$$\int f(x)dx = F(x) + C$$',
  '',
  '### 定积分',
  '定积分的几何意义是曲边梯形的面积。牛顿-莱布尼茨公式：',
  '',
  '$$\int_a^b f(x)dx = F(b) - F(a)$$',
  '',
  '## 应用举例',
  '',
  '### 极值问题',
  '求函数 $f(x) = x^3 - 3x + 2$ 的极值。',
  '',
  '**解**：',
  '1. 求导：$f\'(x) = 3x^2 - 3$',
  '2. 令 $f\'(x) = 0$，得 $x = \\pm 1$',
  '3. 判断：$f\'\'(x) = 6x$',
  '   - $f\'\'(1) = 6 > 0$，$x = 1$ 为极小值点',
  '   - $f\'\'(-1) = -6 < 0$，$x = -1$ 为极大值点',
  '',
  '## 总结要点',
  '',
  '微积分是高等数学的核心内容，掌握以下要点：',
  '- 极限是微积分的基础',
  '- 导数描述变化率',
  '- 积分是求和的极限',
  '- 微积分基本定理联系导数与积分',
].join('\n');

// 演示文章 2: 随笔类型 - 展示简洁布局、目录功能
const essayContent1 = [
  '# 考研路上的感悟',
  '',
  '## 开始的迷茫',
  '',
  '还记得刚决定考研的时候，整个人都是懵的。面对厚厚的专业课教材、 endless 的英语单词、还有那让人头疼的数学题，真的不知道从何下手。',
  '',
  '## 逐渐找到节奏',
  '',
  '### 制定计划的重要性',
  '后来我明白了，**好的计划是成功的一半**。每天早起背单词，上午做数学，下午看专业课，晚上总结复盘。规律的生活让我不再焦虑。',
  '',
  '### 心态的调整',
  '考研不只是知识的比拼，更是心态的较量。学会与自己和解，接受自己的不完美，在挫折中成长，这才是考研给我最大的礼物。',
  '',
  '## 那些温暖的瞬间',
  '',
  '- 图书馆里一起奋斗的研友',
  '- 深夜里陪伴我的那盏台灯',
  '- 每次解出一道难题时的喜悦',
  '- 父母默默的支持和鼓励',
  '',
  '## 给后来者的建议',
  '',
  '1. **早做准备**：不要等到大三下才开始，越早越好',
  '2. **坚持运动**：身体是革命的本钱',
  '3. **学会休息**：劳逸结合，效率更高',
  '4. **相信自己**：你比想象中更强大',
  '',
  '## 结语',
  '',
  '考研是一场修行，路上有苦有甜。但当你走过这段路，回头看时，会发现那个咬牙坚持的自己，真的很了不起。',
  '',
  '> 愿每一个努力的人，都能得偿所愿。',
].join('\n');

export const mockNotes: Note[] = [
  {
    id: 'demo-note-1',
    type: 'note',
    title: '高等数学 - 微积分核心知识点全景总结',
    content: noteContent1,
    subject: 'math',
    tags: ['微积分', '导数', '积分', '极限', '考研数学'],
    videos: [
      { 
        id: 'bilibili-BV1n281ePEd9-1',
        platform: 'bilibili',
        title: '高等数学 微积分精讲班',
        bilibili: { bvid: 'BV1n281ePEd9', p: 1, title: '高等数学 微积分精讲班' },
      },
      { 
        id: 'bilibili-BV1GJ411s7sF-1',
        platform: 'bilibili',
        title: '考研数学高数基础班',
        bilibili: { bvid: 'BV1GJ411s7sF', p: 1, title: '考研数学高数基础班' },
      },
    ],
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=400&fit=crop',
    createdAt: new Date('2026-04-20'),
    updatedAt: new Date('2026-04-21'),
    isPublished: true,
  },
  {
    id: 'demo-essay-1',
    type: 'essay',
    title: '考研路上的感悟：坚持与成长',
    content: essayContent1,
    tags: ['心情', '感悟', '考研', '成长'],
    coverImage: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800&h=400&fit=crop',
    createdAt: new Date('2026-04-19'),
    updatedAt: new Date('2026-04-21'),
    isPublished: true,
  },
  {
    id: 'demo-problem-1',
    type: 'problem',
    title: '线性代数 - 矩阵与行列式经典题集',
    content: '',
    subject: 'math',
    tags: ['线性代数', '矩阵', '行列式', '考研真题'],
    problems: [
      {
        id: 'demo-p1',
        type: 'choice',
        difficulty: 'easy',
        question: '设 $A$ 为 $n$ 阶方阵，若 $|A| = 0$，则下列说法正确的是？',
        options: [
          { label: 'A', content: '$A$ 可逆' },
          { label: 'B', content: '$A$ 的秩为 $n$' },
          { label: 'C', content: '$A$ 的列向量线性相关' },
          { label: 'D', content: '齐次方程组 $Ax = 0$ 只有零解' },
        ],
        answer: 'C',
        explanation: '当 $|A| = 0$ 时，矩阵 $A$ 不可逆，秩 $r(A) < n$，列向量线性相关，齐次方程组 $Ax = 0$ 有非零解。因此选 C。',
        source: '基础概念题',
        tags: ['行列式', '矩阵', '线性相关'],
      },
      {
        id: 'demo-p2',
        type: 'choice',
        difficulty: 'medium',
        question: '设 $A = \\begin{pmatrix} 1 & 2 & 3 \\\\ 2 & 4 & 6 \\\\ 3 & 6 & 9 \\end{pmatrix}$，则 $r(A) = ?$',
        options: [
          { label: 'A', content: '0' },
          { label: 'B', content: '1' },
          { label: 'C', content: '2' },
          { label: 'D', content: '3' },
        ],
        answer: 'B',
        explanation: '观察矩阵 $A$，第二行是第一行的 2 倍，第三行是第一行的 3 倍，所以三行成比例，矩阵的秩为 1。',
        source: '2024年考研数学一',
        tags: ['矩阵', '秩', '行列式'],
      },
      {
        id: 'demo-p3',
        type: 'calculation',
        difficulty: 'medium',
        question: '计算行列式 $D = \\begin{vmatrix} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\\\ 7 & 8 & 9 \\end{vmatrix}$',
        answer: '0',
        explanation: '**解法一**：直接计算\n\n$$D = 1 \\times (5 \\times 9 - 6 \\times 8) - 2 \\times (4 \\times 9 - 6 \\times 7) + 3 \\times (4 \\times 8 - 5 \\times 7)$$\n$$= 1 \\times (-3) - 2 \\times (-6) + 3 \\times (-3) = -3 + 12 - 9 = 0$$\n\n**解法二**：观察法\n\n第三列 = 第一列 + 第二列，所以三列线性相关，行列式为 0。',
        source: '经典例题',
        tags: ['行列式', '计算'],
      },
      {
        id: 'demo-p4',
        type: 'calculation',
        difficulty: 'hard',
        question: '设 $A$ 为 $n$ 阶矩阵，满足 $A^2 = A$，证明：$r(A) + r(A - E) = n$，其中 $E$ 为单位矩阵。',
        answer: '证明见解析',
        explanation: '**证明**：\n\n由 $A^2 = A$ 得 $A(A - E) = 0$。\n\n根据 Sylvester 不等式：$r(AB) \\geq r(A) + r(B) - n$\n\n取 $B = A - E$，则 $r(A(A-E)) = r(0) = 0$\n\n所以 $0 \\geq r(A) + r(A-E) - n$\n\n即 $r(A) + r(A-E) \\leq n$ ... ①\n\n又因为 $A + (E-A) = E$，所以 $r(A) + r(E-A) \\geq r(E) = n$\n\n而 $r(E-A) = r(A-E)$\n\n所以 $r(A) + r(A-E) \\geq n$ ... ②\n\n由 ①② 得：$r(A) + r(A-E) = n$\n\n**证毕**。',
        source: '2023年考研数学一压轴题',
        tags: ['矩阵', '秩', '证明题'],
        tips: '利用 Sylvester 不等式和矩阵秩的性质',
      },
      {
        id: 'demo-p5',
        type: 'fill',
        difficulty: 'easy',
        question: '若 $A$ 为 3 阶矩阵，且 $|A| = 2$，则 $|2A| = $ ______。',
        answer: '16',
        explanation: '根据行列式的性质：$|kA| = k^n|A|$，其中 $n$ 为矩阵阶数。所以 $|2A| = 2^3 \\times 2 = 16$。',
        source: '基础练习题',
        tags: ['行列式', '性质'],
      },
      {
        id: 'demo-p6',
        type: 'calculation',
        difficulty: 'hard',
        question: '设 $A = \\begin{pmatrix} 2 & 1 & 1 \\\\ 1 & 2 & 1 \\\\ 1 & 1 & 2 \\end{pmatrix}$，求 $A$ 的特征值和特征向量。',
        answer: '特征值：$\\lambda_1 = \\lambda_2 = 1, \\lambda_3 = 4$；特征向量见解析',
        explanation: '**解**：\n\n**第一步**：求特征值\n\n$$|\\lambda E - A| = \\begin{vmatrix} \\lambda-2 & -1 & -1 \\\\ -1 & \\lambda-2 & -1 \\\\ -1 & -1 & \\lambda-2 \\end{vmatrix}$$\n\n令 $x = \\lambda - 2$，则：\n\n$$= \\begin{vmatrix} x & -1 & -1 \\\\ -1 & x & -1 \\\\ -1 & -1 & x \\end{vmatrix} = (x-1)^2(x+2)$$\n\n所以 $\\lambda_1 = \\lambda_2 = 1, \\lambda_3 = 4$\n\n**第二步**：求特征向量\n\n当 $\\lambda = 1$ 时，解 $(E-A)x = 0$，得基础解系：\n$\\xi_1 = (1, -1, 0)^T, \\xi_2 = (1, 0, -1)^T$\n\n当 $\\lambda = 4$ 时，解 $(4E-A)x = 0$，得基础解系：\n$\\xi_3 = (1, 1, 1)^T$',
        source: '2025年考研数学一',
        tags: ['特征值', '特征向量', '计算'],
      },
    ],
    createdAt: new Date('2026-04-18'),
    updatedAt: new Date('2026-04-21'),
    isPublished: true,
  },
];
